name: Deploy

on:
  push:
    branches: [dev, main]

jobs:
  deploy-dev:
    if: github.ref == 'refs/heads/dev'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Deploy to Vercel (Development)
        run: |
          npm install --global vercel
          vercel --token ${{ secrets.VERCEL_TOKEN }} --confirm --name packvote-coming-soon --scope ${{ secrets.VERCEL_ORG_ID }} --env NEXT_PUBLIC_SUPABASE_URL=${{ secrets.SUPABASE_URL }} --env NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }} --env NEXT_PUBLIC_SUPABASE_SCHEMA=dev

  deploy-prod:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: [build]
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Deploy to Vercel (Production)
        run: |
          npm install --global vercel
          vercel --token ${{ secrets.VERCEL_TOKEN }} --prod --confirm --name packvote-coming-soon --scope ${{ secrets.VERCEL_ORG_ID }} --env NEXT_PUBLIC_SUPABASE_URL=${{ secrets.SUPABASE_URL }} --env NEXT_PUBLIC_SUPABASE_ANON_KEY=${{ secrets.SUPABASE_ANON_KEY }} --env NEXT_PUBLIC_SUPABASE_SCHEMA=public
  
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.x'
      - name: Install dependencies
        run: npm ci
      - name: Build
        run: npm run build
        env:
          CI: true 